# Generated by Django 3.2.2 on 2021-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masjid',
            name='fajr',
            field=models.DateField(),
        ),
    ]
